image: nixos/19.03
packages:
  - nixpkgs.git
  - nixpkgs.nodejs-10_x
  - nixpkgs.nodePackages.lerna
  - nixpkgs.nodePackages.yarn
repositories:
  nixpkgs: https://nixos.org/channels/nixos-19.03
sources:
  - https://git.sr.ht/~madnat/overture
secrets:
  - bf387dfb-e183-4fc1-bd6e-01b16c209101
tasks:
  - setup: |
      cd overture
      nix-shell --command 'lerna bootstrap'
  - test: |
      cd overture
      nix-shell --command 'lerna run test'
  - build: |
      cd overture
      nix-shell --command 'lerna run build'
  - mirror: |
      cd overture
      git remote add github https://jkopanski@github.com/jkopanski/overture.git
      git push --prune github '+refs/remotes/origin/*:refs/heads/*' '+refs/tags/*:refs/tags/*'
